version: '3.9'

services: 
  sql:
      container_name: data-sql
      image: mysql
      ports:
        - "3307:3306"
      env_file:
        - ./.env
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_USERNAME=${DB_USERNAME}
        - MYSQL_AUTH_PLUGIN=caching_sha2_password
        - TZ=Asia/Seoul
      command:
        - --default-authentication-plugin=caching_sha2_password
        - --collation-server=utf8mb4_unicode_ci
        - --character-set-server=utf8mb4
        - --lower_case_table_names=1
      volumes:
        - sqlVolume:/var/lib/mysql
        - ./my-init:/etc/mysql/my.cnf
      healthcheck:
        test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
        interval: 10s
        timeout: 2s
        retries: 100

  backend:
    container_name: data-django
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend
      - static-volume:/backend/config/static/
    command:
      - /bin/sh
      - -c
      - /usr/src/local/entrypoint.sh
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      sql:
        condition: service_healthy      

  ngnix:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: data-nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/con.f/nginx-setup.conf
      - static-volume:/backend/config/static/

    depends_on:
      - backend
      

volumes:
  sqlVolume: {}
  nginx:
  backend:
  build_file:
  static-volume: